# Generated by Django 5.1.6 on 2025-09-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_is_popular_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('medicine', 'Medicine'), ('cosmetic', 'Cosmetic'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
